"""
texture_report_formatter.py — Human-Readable Texture Forensic Reports
═══════════════════════════════════════════════════════════════════════════════

Converts TextureAnalysisResult into detailed forensic reports suitable for
analysts and presentation.

Report Format:
  • Executive Summary (verdict + confidence)
  • Detailed Zone Analysis (per-zone forensic breakdown)
  • Forensic Findings (anomalies detected)
  • Thresholds & Reasoning (explainability)
  • Recommendations (for human review)
"""

from __future__ import annotations

import json
from typing import Dict, List
from dataclasses import dataclass

from agents.texture_agent import TextureAnalysisResult, Thresholds


@dataclass
class TextureForensicReport:
    """Complete forensic report on image texture."""
    
    case_id: str
    image_path: str
    verdict: str  # "AUTHENTIC", "SUSPICIOUS", "LIKELY FAKE", "DEEPFAKE"
    confidence: float  # [0, 1]
    texture_probability: float
    
    executive_summary: str
    zone_analysis: str
    forensic_findings: str
    recommendations: str
    
    # Raw data for programmatic access
    detailed_metrics: Dict
    
    def to_json(self) -> str:
        return json.dumps({
            "case_id": self.case_id,
            "image_path": self.image_path,
            "verdict": self.verdict,
            "confidence": self.confidence,
            "texture_probability": self.texture_probability,
            "executive_summary": self.executive_summary,
            "zone_analysis": self.zone_analysis,
            "forensic_findings": self.forensic_findings,
            "recommendations": self.recommendations,
            "detailed_metrics": self.detailed_metrics,
        }, indent=2)
    
    def to_markdown(self) -> str:
        """Generate Markdown report."""
        md = f"""# Texture Forensic Analysis Report
**Case ID:** {self.case_id}
**Image:** {self.image_path}
**Analysis Date:** 2026-04-24

---

## ⚖️ Verdict

**Status:** {self.verdict}
**Confidence:** {self.confidence:.1%}
**Texture Fake Probability:** {self.texture_probability:.1%}

---

## 📋 Executive Summary

{self.executive_summary}

---

## 🔬 Detailed Zone Analysis

{self.zone_analysis}

---

## 🔍 Forensic Findings

{self.forensic_findings}

---

## 💡 Recommendations

{self.recommendations}

---

*Report generated by Texture Agent — TAD (2024) + NPR (CVPR 2024)*
"""
        return md
    
    def to_text(self) -> str:
        """Generate plain text report."""
        text = f"""
╔════════════════════════════════════════════════════════════════════════════════╗
║                    TEXTURE FORENSIC ANALYSIS REPORT                           ║
╚════════════════════════════════════════════════════════════════════════════════╝

Case ID: {self.case_id}
Image:   {self.image_path}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

VERDICT: {self.verdict}
Confidence:                  {self.confidence:.1%}
Texture Fake Probability:    {self.texture_probability:.1%}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EXECUTIVE SUMMARY

{self.executive_summary}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DETAILED ZONE ANALYSIS

{self.zone_analysis}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

FORENSIC FINDINGS

{self.forensic_findings}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

RECOMMENDATIONS

{self.recommendations}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""
        return text


class TextureReportFormatter:
    """Format texture analysis results into forensic reports."""
    
    def __init__(self):
        self.thresholds = Thresholds()
    
    def format_report(
        self,
        case_id: str,
        image_path: str,
        result: TextureAnalysisResult
    ) -> TextureForensicReport:
        """
        Generate complete forensic report.
        
        Args:
            case_id: Unique case identifier
            image_path: Path to analyzed image
            result: TextureAnalysisResult from TextureAgent
        
        Returns:
            TextureForensicReport with formatted narrative
        """
        # Determine verdict
        verdict, confidence = self._determine_verdict(result.texture_fake_probability)
        
        # Generate narrative sections
        executive_summary = self._generate_executive_summary(result, verdict)
        zone_analysis = self._generate_zone_analysis(result)
        forensic_findings = self._generate_forensic_findings(result)
        recommendations = self._generate_recommendations(result, verdict)
        
        # Detailed metrics
        detailed_metrics = result.to_dict()
        
        return TextureForensicReport(
            case_id=case_id,
            image_path=image_path,
            verdict=verdict,
            confidence=confidence,
            texture_probability=result.texture_fake_probability,
            executive_summary=executive_summary,
            zone_analysis=zone_analysis,
            forensic_findings=forensic_findings,
            recommendations=recommendations,
            detailed_metrics=detailed_metrics,
        )
    
    def _determine_verdict(self, fake_prob: float) -> tuple[str, float]:
        """Determine verdict and confidence from probability."""
        if fake_prob > 0.85:
            return "DEEPFAKE DETECTED", min(1.0, (fake_prob - 0.70) / 0.30)
        elif fake_prob > 0.70:
            return "LIKELY FAKE", min(1.0, (fake_prob - 0.50) / 0.20)
        elif fake_prob > 0.50:
            return "SUSPICIOUS", abs(fake_prob - 0.5) * 2
        else:
            return "LIKELY AUTHENTIC", 1.0 - abs(fake_prob - 0.5) * 2
    
    def _generate_executive_summary(
        self,
        result: TextureAnalysisResult,
        verdict: str
    ) -> str:
        """Generate high-level summary."""
        prob = result.texture_fake_probability
        
        # Count critical zones
        critical_zones = [
            z for z in result.zone_results.values()
            if z.risk_level == "critical"
        ]
        elevated_zones = [
            z for z in result.zone_results.values()
            if z.risk_level == "elevated"
        ]
        
        lines = [
            f"The texture analysis indicates a {prob:.0%} probability of synthetic or manipulated content.",
            ""
        ]
        
        if verdict.startswith("DEEPFAKE") or verdict == "LIKELY FAKE":
            lines.append(
                "Multiple forensic indicators show artifacts consistent with GAN upsampling, "
                "over-smoothing, and boundary blending artifacts. The analysis detected:"
            )
            
            if critical_zones:
                zones_str = ", ".join([z.zone_name for z in critical_zones])
                lines.append(f"  • Critical anomalies in zones: {zones_str}")
            
            if elevated_zones:
                zones_str = ", ".join([z.zone_name for z in elevated_zones])
                lines.append(f"  • Elevated risk in zones: {zones_str}")
            
            if result.seam_detected:
                lines.append(
                    "  • Boundary seam artifacts detected (inconsistent texture at jaw-neck boundary)"
                )
            
            if result.lbp_uniformity < self.thresholds.LBP_UNIFORM_ELEVATED:
                lines.append(
                    "  • Abnormally high skin tone uniformity (GAN oversmoothing signature)"
                )
            
        else:
            lines.append(
                "Texture analysis shows natural variation patterns consistent with authentic "
                "or minimally processed images. No major forensic artifacts detected."
            )
        
        lines.append(
            f"\n**Confidence Level:** {prob:.1%} for fake classification"
        )
        
        return "\n".join(lines)
    
    def _generate_zone_analysis(self, result: TextureAnalysisResult) -> str:
        """Generate per-zone detailed analysis."""
        lines = []
        
        # Define zone risk levels
        risk_emoji = {
            "critical": "🔴",
            "elevated": "🟡",
            "normal": "🟢"
        }
        
        # Group zones by risk
        zones_by_risk = {}
        for zone_name, zone_result in result.zone_results.items():
            risk = zone_result.risk_level
            if risk not in zones_by_risk:
                zones_by_risk[risk] = []
            zones_by_risk[risk].append(zone_result)
        
        # Critical zones
        if "critical" in zones_by_risk:
            lines.append("### Critical Risk Zones (Highest Confidence Anomalies)\n")
            for zone in zones_by_risk["critical"]:
                lines.append(f"**{zone.zone_name.upper()}**")
                lines.append(f"  Emoji: {risk_emoji['critical']}")
                lines.append(f"  EMD (texture uniformity distance):     {zone.emd_score:.4f}")
                lines.append(f"  LBP uniformity (skin smoothness):      {zone.lbp_uniformity:.1%}")
                if zone.lbp_uniformity < 0.70:
                    lines.append(f"    → WARNING: Unusually uniform (authentic skin: 80%+)")
                lines.append(f"  NPR residual (upsampling detection):   {zone.npr_residual:.4f}")
                if zone.npr_residual > 0.18:
                    lines.append(f"    → WARNING: Characteristic GAN upsampling pattern detected")
                lines.append(f"  Texture variance (Gabor):              {zone.texture_variance:.5f}")
                if zone.texture_variance < 0.015:
                    lines.append(f"    → WARNING: Very low micro-texture variance (GAN signature)")
                if zone.color_delta_e is not None:
                    lines.append(f"  Color uniformity (ΔE):                 {zone.color_delta_e:.2f}")
                    if zone.color_delta_e < 3.0:
                        lines.append(f"    → WARNING: Unnaturally uniform skin tone")
                lines.append("")
        
        # Elevated zones
        if "elevated" in zones_by_risk:
            lines.append("### Elevated Risk Zones (Suspicious Patterns)\n")
            for zone in zones_by_risk["elevated"]:
                lines.append(f"**{zone.zone_name}**")
                lines.append(f"  Emoji: {risk_emoji['elevated']}")
                lines.append(f"  EMD: {zone.emd_score:.4f} | LBP: {zone.lbp_uniformity:.1%} | NPR: {zone.npr_residual:.4f}")
                lines.append("")
        
        # Normal zones
        if "normal" in zones_by_risk:
            normal_names = [z.zone_name for z in zones_by_risk["normal"]]
            lines.append(f"### Normal Zones (No Major Anomalies)\n")
            lines.append(f"{', '.join(normal_names)}\n")
        
        return "\n".join(lines)
    
    def _generate_forensic_findings(self, result: TextureAnalysisResult) -> str:
        """Generate detailed forensic findings."""
        findings = []
        
        # Finding 1: EMD-based zone comparison
        avg_emd = (result.jaw_emd + result.neck_emd + result.cheek_emd) / 3.0
        findings.append(f"### 1. Zone Texture Consistency (TAD Metric)\n")
        findings.append(f"Average EMD: {avg_emd:.4f}")
        
        if avg_emd < self.thresholds.EMD_AUTHENTIC:
            findings.append(
                f"✓ AUTHENTIC PATTERN: Natural variation in skin texture across zones ({avg_emd:.4f} < {self.thresholds.EMD_AUTHENTIC})"
            )
        elif avg_emd > self.thresholds.EMD_ANOMALOUS:
            findings.append(
                f"⚠ ANOMALOUS: Artificially uniform texture across zones ({avg_emd:.4f} > {self.thresholds.EMD_ANOMALOUS}) — "
                f"consistent with GAN generation where upsampling produces similar texture statistics"
            )
        else:
            findings.append(
                f"? BORDERLINE: Moderate EMD ({avg_emd:.4f}) — requires additional signals for classification"
            )
        
        findings.append("")
        
        # Finding 2: LBP uniformity
        findings.append(f"### 2. Skin Smoothness Analysis (LBP Histogram)\n")
        findings.append(f"LBP Uniformity: {result.lbp_uniformity:.1%}")
        
        if result.lbp_uniformity > self.thresholds.LBP_UNIFORM_AUTHENTIC:
            findings.append(
                f"✓ CONSISTENT WITH AUTHENTIC: Natural skin has {result.lbp_uniformity:.0%} uniform LBP patterns"
            )
        elif result.lbp_uniformity < self.thresholds.LBP_UNIFORM_CRITICAL:
            findings.append(
                f"🔴 CRITICAL GAN SIGNATURE: LBP uniformity of {result.lbp_uniformity:.0%} is unnaturally high. "
                f"GAN-generated skin typically shows 60-75% uniformity due to oversmoothing in upsampling. "
                f"Authentic skin: 80%+ uniform patterns."
            )
        else:
            findings.append(
                f"🟡 ELEVATED RISK: LBP uniformity ({result.lbp_uniformity:.0%}) suggests possible upsampling artifacts"
            )
        
        findings.append("")
        
        # Finding 3: NPR residuals
        npr_residuals = [z.npr_residual for z in result.zone_results.values()]
        avg_npr = np.mean(npr_residuals) if npr_residuals else 0.1
        findings.append(f"### 3. Upsampling Artifact Detection (NPR Metric)\n")
        findings.append(f"Average NPR Residual: {avg_npr:.4f}")
        
        if avg_npr > self.thresholds.NPR_ANOMALOUS:
            findings.append(
                f"🔴 UPSAMPLING ARTIFACTS DETECTED: High NPR residual ({avg_npr:.4f}) indicates "
                f"characteristic 4-connectivity vs 8-connectivity mismatch from GAN upsampling. "
                f"This pattern persists across different upsampling operators (nearest-neighbor, "
                f"bilinear, transposed convolution) commonly used in face generation models."
            )
        elif avg_npr < self.thresholds.NPR_AUTHENTIC:
            findings.append(
                f"✓ AUTHENTIC PATTERN: Low NPR residual ({avg_npr:.4f}) consistent with natural "
                f"pixel relationships in authentic photography"
            )
        else:
            findings.append(
                f"? BORDERLINE: NPR residual in intermediate range ({avg_npr:.4f})"
            )
        
        findings.append("")
        
        # Finding 4: Boundary seams
        findings.append(f"### 4. Boundary Artifact Detection\n")
        if result.seam_detected:
            findings.append(
                f"🔴 SEAM ARTIFACT DETECTED: Significant texture discontinuity at jaw-neck boundary "
                f"(dissimilarity: {result.jaw_emd:.4f}). This is a signature of face-swap blending where "
                f"the forged face region is imperfectly blended with the original neck/shoulders."
            )
        else:
            findings.append(
                f"✓ NO BOUNDARY ARTIFACTS: Texture transitions smoothly across facial boundaries"
            )
        
        findings.append("")
        
        # Finding 5: Multi-scale consistency
        findings.append(f"### 5. Resampling Robustness\n")
        findings.append(f"Multi-Scale Consistency: {result.multi_scale_consistency:.1%}")
        findings.append(
            f"This metric measures whether texture patterns remain consistent when the image is "
            f"downsampled and upsampled. GAN-generated faces often fail this test because "
            f"they're trained on specific resolutions and compression artifacts reveal themselves "
            f"at different scales."
        )
        
        return "\n".join(findings)
    
    def _generate_recommendations(
        self,
        result: TextureAnalysisResult,
        verdict: str
    ) -> str:
        """Generate analyst recommendations."""
        recs = []
        
        recs.append("### For Analysts\n")
        
        if verdict.startswith("DEEPFAKE") or verdict == "LIKELY FAKE":
            recs.append(
                "1. **ELEVATE TO HIGH CONFIDENCE**: Texture forensics show multiple convergent "
                "indicators of synthesis. Recommend flagging for secondary review with other "
                "detection modalities (frequency, biological plausibility, metadata)."
            )
            recs.append("")
            recs.append(
                "2. **EXAMINE BOUNDARY REGIONS**: Inspect jaw-neck transition, cheek-jaw seams, "
                "and perioral region (lips) visually. These zones are highest-risk for blending artifacts."
            )
            recs.append("")
            recs.append(
                "3. **GENERATOR HYPOTHESIS**: Based on LBP/NPR signatures, likely generators are:"
            )
            recs.append(
                "     • StyleGAN / StyleGAN2 (if strong uniformity signal)"
            )
            recs.append(
                "     • Face-Swap or Deepfaceslab (if strong boundary seam signal)"
            )
            recs.append(
                "     • Diffusion models (if sharp EMD changes)"
            )
        
        elif verdict == "SUSPICIOUS":
            recs.append(
                "1. **INCONCLUSIVE**: Texture alone cannot determine authenticity. "
                "Recommend multi-factor fusion with:"
            )
            recs.append("     • Frequency analysis (FFT magnitude statistics)")
            recs.append("     • Biological plausibility (facial landmark geometry)")
            recs.append("     • Metadata analysis (EXIF, compression artifacts)")
            recs.append("")
            recs.append(
                "2. **MANUAL INSPECTION**: Carefully examine the face for visual artifacts, "
                "particularly skin tone gradients and eye reflections."
            )
        
        else:  # AUTHENTIC
            recs.append(
                "1. **LIKELY AUTHENTIC**: Texture forensics show natural patterns. "
                "However, texture alone is not conclusive for high-quality deepfakes. "
                "Recommend confirmatory analysis with other modalities."
            )
            recs.append("")
            recs.append(
                "2. **CONTINUE MONITORING**: Even if authentic by texture, check frequency analysis "
                "and metadata for compression anomalies that indicate prior manipulation."
            )
        
        recs.append("")
        recs.append("### Calibration Note\n")
        recs.append(
            f"This probability ({result.texture_fake_probability:.1%}) is calibrated on:\n"
            f"  • FF++ (FaceForensics++) with 8 manipulation methods\n"
            f"  • Celeb-DF v2 (high-quality DeepFaceLab videos)\n"
            f"  • DFDC (Deepfake Detection Challenge)\n\n"
            f"Out-of-distribution deepfakes (new generators, compression methods) "
            f"may have different score distributions."
        )
        
        return "\n".join(recs)


# Utility helper
import numpy as np


if __name__ == "__main__":
    print("TextureReportFormatter module loaded")
